version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lees-sam-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ztlobt4dlgdb"
s3_prefix = "lees-sam-demo"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
