# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  LeesDemoAPIGW:
    Type: AWS::Serverless::Api
    Properties:
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis-lambda-authorizer.html
      Auth:
        DefaultAuthorizer: MyAuthFn
        Authorizers:
          MyAuthFn:
            FunctionArn: !GetAtt SimpleTokenAuth.Arn
      Description: Lee's demo api gateway
      Name: lees-demo-api
      OpenApiVersion: "3.0.0"
      StageName: v0
      Tags:
        DeleteMe: yes
        Env: test
      TracingEnabled: yes
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"

  SimpleTokenAuth:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth.handler
      Runtime: nodejs14.x

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  apiEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          LM_S3_BUCKET: !Ref leesDemoIOBkt
          LM_STATE_MACHINE_ARN: !Ref MyStepFunction 
      Handler: src/handlers/api-endpoint.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref leesDemoIOBkt
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt MyStepFunction.Name
      Events:
        GETFoo:
          Type: Api
          Properties:
            Path: /foo
            Method: get
            RestApiId:
              Ref: LeesDemoAPIGW
        POSTFoo:
          Type: Api
          Properties:
            Path: /foo
            Method: post
            RestApiId:
              Ref: LeesDemoAPIGW
        BucketItemEvent:
          Type: S3
          Properties:
            Bucket: !Ref leesDemoSourceBkt
            Events: s3:ObjectCreated:*

  leesDemoSourceBkt:
    Type: AWS::S3::Bucket
  
  leesDemoIOBkt:
    Type: AWS::S3::Bucket

  MyStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine.asl.json
      DefinitionSubstitutions:
        MakeInputFunctionArn: !GetAtt MakeInputFunction.Arn
        ProcessTaskFunctionArn: !GetAtt ProcessFunction.Arn
        ErrorFunctionArn: !GetAtt ErrorFunction.Arn
        SuccessFunctionArn: !GetAtt SuccessFunction.Arn
      Name: lees-demo-step-function
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref MakeInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SuccessFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ErrorFunction

  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/process.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref leesDemoIOBkt
      Environment:
        Variables:
          LM_S3_BUCKET: !Ref leesDemoIOBkt

  MakeInputFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/input.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref leesDemoIOBkt
      Environment:
        Variables:
          LM_S3_BUCKET: !Ref leesDemoIOBkt

  SuccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/success.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref leesDemoIOBkt
      Environment:
        Variables:
          LM_S3_BUCKET: !Ref leesDemoIOBkt
  
  ErrorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/error.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref leesDemoIOBkt
      Environment:
        Variables:
          LM_S3_BUCKET: !Ref leesDemoIOBkt
